org: jamesinfotrack
app: infotrack-fe-dev-test
service: infotrack-fe-dev-test

frameworkVersion: "2"

provider:
  name: aws
  runtime: nodejs12.x
  lambdaHashingVersion: "20201221"

functions:
  api:
    handler: handler.api
    events:
      - http:
          path: /
          method: get
  titles:
    handler: handler.titles
    events:
      - http:
          path: /titles
          method: post
